language: r
sudo: required
dist: trusty

cache: packages

matrix:
  include:
    - r: bioc-devel
      compiler: gcc
    - r: bioc-devel
      compiler: clang
      os: osx
    - r: bioc-release
      compiler: gcc
    - r: bioc-release
      compiler: clang
      os: osx

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

before_install:
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user 'tensorflow==1.14.0'
  - pip install --user 'tensorflow-probability==0.5.0'


r_packages:
  - devtools
  - covr
  - testthat
  - lintr
  - styler

bioc_packages:
  - BiocCheck

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
