language: r
sudo: required
dist: bionic

cache: packages

matrix:
  include:
    - r: devel
      compiler: gcc
    - r: release
      compiler: gcc

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

r_packages:
  - reticulate
  - tensorflow
  - tfprobability
  - devtools
  - covr
  - testthat
  - lintr
  - styler
  - knitr
  - rmarkdown
  - lassoshooting
  - glmnet
  - LaplacesDemon
  - grplasso

before_install:
  - export DISPLAY=:99.0

before_script:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip
  - R -e 'reticulate::install_miniconda()'
  - R -e 'reticulate::conda_create("r-reticulate", packages = c("python==3.7"))'
  - R -e 'tensorflow::install_tensorflow(version = "2.3.0")'
  - R -e 'tfprobability::install_tfprobability(version="0.11.0")'
  - R -e 'tensorflow::tf_config()'

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
