language: r

sudo: required
dist: trusty

cache: packages

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

r_packages:
  - covr
  - testthat

r_github_packages:
  - jimhester/lintr

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

before_script:
  - autoreconf -vif
  - ./configure

after_success:
  - Rscript -e 'library(covr); codecov()'
