language: r
sudo: required
dist: trusty

cache: packages

matrix:
  include:
    - compiler: gcc
      r: bioc-devel
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: gcc
      r: bioc-release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

r_packages:
  - devtools
  - covr
  - testthat
  - lintr

addons:
  apt:
    packages:
      - cmake
      - cmake-data
    sources:
      - kalakris-cmake

bioc_packages:
  - BiocCheck

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade autoconf
  - sudo apt-get install --only-upgrade automake
  - sudo apt-get install --only-upgrade autotools-dev
  - sudo apt-get install autoconf-archive
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libopenblas-dev liblapack-dev
  - sudo apt-get install libarmadillo-dev
  - sudo apt-get install libhdf5-dev

before_script:
  - autoreconf -vif

after_script:
  - mkdir build && cd build
  - cmake ..
  - make && make test
  - ./netReg -h

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
