language: r
sudo: required
dist: trusty

matrix:
  include:
    - r: devel
      compiler: gcc
    - r: release
      compiler: gcc

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R -e 'tfprobability::install_tfprobability(version = "0.10.0", tensorflow = "2.2.0")'
  - R -e 'tensorflow::tf_config()'

r_packages:
  - tensorflow
  - tfprobability
  - devtools
  - covr
  - testthat
  - lintr
  - styler
  - knitr
  - rmarkdown
  - lassoshooting
  - glmnet
  - LaplacesDemon
  - grplasso

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
