name: ci

on:
  push:
  pull_request:

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macOS-latest', 'ubuntu-18.04']
        tfp: ['0.11']
        include:
          - os: ubuntu-18.04
            cran: https://demo.rstudiopm.com/all/__linux__/bionic/latest
          - tfp: '0.11'
            tf: '2.3.0'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (TFP ${{ matrix.tfp }}, TF ${{matrix.tf}})
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      TF_VERSION: ${{ matrix.tf }}
      TFP_VERSION: ${{ matrix.tfp }}
      PIP_NO_WARN_SCRIPT_LOCATION: false
      RETICULATE_AUTOCONFIGURE: 'FALSE'
      CRAN: ${{ matrix.cran }}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          sudo apt-get install -y qpdf
      - name: install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"
      - name: install Python
        run: |
          Rscript -e "remotes::install_github('rstudio/reticulate')"
          Rscript -e "reticulate::install_miniconda()"
          Rscript -e "reticulate::conda_create('r-reticulate', packages = c('python==3.6.9'))"
      - name: install TensorFlow
        run: |
          Rscript -e "remotes::install_local()"
          Rscript -e "tfprobability::install_tfprobability(version=Sys.getenv('TFP_VERSION'), tensorflow=Sys.getenv('TF_VERSION'))"
      - name: check
        continue-on-error: ${{ contains(matrix.allow_failure, 'true') }}
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual --no-build-vignettes', error_on = 'warning', check_dir = 'check')"
      - name: coverage
        continue-on-error: true
        run: |
          tar -C .. -xf $PKG_TARBALL- Rscript -e 'covr::codecov()'
          Rscript -e 'lintr::lint_package()'

